module Facet

  class Compiler

    def self.compile(template_name : String, nodes : Array(Node)) : String
      safe_name = template_name.gsub(/[^a-zA-Z0-9_]/, "_")
      out = String::Builder.new

      out << "# GENERATED by Facet::Compiler — do not edit\n"
      out << "module Facet\n"
      out << "  module Templates\n"
      out << "    def self.render_#{safe_name}(ctx : Facet::Context) : String\n"
      out << "      _out = String::Builder.new\n\n"

      nodes.each do |node|
        case node

        when HtmlNode
          escaped = node.content.gsub("\\", "\\\\\\\\").gsub("\"", "\\\"").gsub("\n", "\\n").gsub("\r", "")
          out << "      _out << \"#{escaped}\"\n"

        when CodeNode
          if node.init
            out << "      # --- init block ---\n"
            out << indent(node.source, 6)
            out << "\n      # --- end init ---\n"
            out << "      _js = Facet::BindingCompiler.compile_to_js(Facet::BindingRegistry.flush)\n\n"
          else
            out << "      # --- render block ---\n"
            out << "      _block_result = begin\n"
            out << indent(node.source, 8)
            out << "\n      end\n"
            out << "      _out << _block_result.to_s if _block_result\n\n"
          end
        end
      end

      out << "      _html = _out.to_s\n"
      out << "      _html = _html.sub(\"</body>\", \"\#{_js}\\n</body>\") if _js && !_js.empty?\n"
      out << "      _html\n"
      out << "    end\n"
      out << "  end\n"
      out << "end\n"

      out.to_s
    end

    private def self.indent(source : String, spaces : Int32) : String
      pad = " " * spaces
      source.lines.map { |l| "#{pad}#{l.chomp}" }.join("\n")
    end
  end
end